// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvXm4Drg-HLjaPnxjl3imwt4kySh_4Qbk',
    appId: '1:876040075403:web:1e7bf192d8a15a88877c8e',
    messagingSenderId: '876040075403',
    projectId: 'ifound-8fb26',
    authDomain: 'ifound-8fb26.firebaseapp.com',
    storageBucket: 'ifound-8fb26.firebasestorage.app',
    measurementId: 'G-F484CH77ED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1LHqZBk93jrbmJWLtpPQ5b7-YFn3fToQ',
    appId: '1:876040075403:android:932ba3e6a9b92e07877c8e',
    messagingSenderId: '876040075403',
    projectId: 'ifound-8fb26',
    storageBucket: 'ifound-8fb26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxWEskZiTrsb33YlSyvI3Tc5MnkwjeG7c',
    appId: '1:876040075403:ios:c121bfa19c02af82877c8e',
    messagingSenderId: '876040075403',
    projectId: 'ifound-8fb26',
    storageBucket: 'ifound-8fb26.firebasestorage.app',
    iosClientId: '876040075403-33obvp97fmuu652nui5apd7apreje1gp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxWEskZiTrsb33YlSyvI3Tc5MnkwjeG7c',
    appId: '1:876040075403:ios:c121bfa19c02af82877c8e',
    messagingSenderId: '876040075403',
    projectId: 'ifound-8fb26',
    storageBucket: 'ifound-8fb26.firebasestorage.app',
    iosClientId: '876040075403-33obvp97fmuu652nui5apd7apreje1gp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvXm4Drg-HLjaPnxjl3imwt4kySh_4Qbk',
    appId: '1:876040075403:web:3d5ba3975bd88e64877c8e',
    messagingSenderId: '876040075403',
    projectId: 'ifound-8fb26',
    authDomain: 'ifound-8fb26.firebaseapp.com',
    storageBucket: 'ifound-8fb26.firebasestorage.app',
    measurementId: 'G-1D3LER7VRF',
  );

}